# -*- coding: utf-8 -*-
"""PosTech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5kd9zyCGy5rD6UTDNLAz02n2hChLCPZ
"""

import pandas as pd
import numpy as np

"""**Verificar se os arquivos estão disponíveis**"""

import os

os.listdir("/content")

"""**Carregar os datasets**"""

customers = pd.read_csv("/content/olist_customers_dataset.csv")

orders = pd.read_csv("/content/olist_orders_dataset.csv")

order_items = pd.read_csv("/content/olist_order_items_dataset.csv")

geolocation = pd.read_csv("/content/olist_geolocation_dataset.csv")

reviews = pd.read_csv("/content/olist_order_reviews_dataset.csv")

products = pd.read_csv("/content/olist_products_dataset.csv")

sellers = pd.read_csv("/content/olist_sellers_dataset.csv")

category_translation = pd.read_csv("/content/product_category_name_translation.csv")

orders.head()

"""**Tamanho de cada tabela**"""

print("customers:", customers.shape)
print("orders:", orders.shape)
print("order_items:", order_items.shape)
print("reviews:", reviews.shape)
print("products:", products.shape)
print("sellers:", sellers.shape)
print("category_translation:", category_translation.shape)
print("geolocation:", geolocation.shape)

"""**Visualizar as primeiras linhas**"""

customers.head()

orders.head()

order_items.head()

geolocation.head()

reviews.head()

products.head()

sellers.head()

category_translation.head()

"""**Nomes das colunas e tipos**"""

customers.info()

customers.info()
orders.info()
order_items.info()
geolocation.info()
reviews.info()
products.info()
sellers.info()
category_translation.info()
geolocation.info()

"""**Verificar nulos**"""

customers.isnull().sum()
orders.isnull().sum()
order_items.isnull().sum()
geolocation.isnull().sum()
reviews.isnull().sum()
products.isnull().sum()
sellers.isnull().sum()
category_translation.isnull().sum()
geolocation.isnull().sum()

"""**Base analítica**"""

df = orders.merge(customers, on="customer_id", how="left") #pedido + cliente.

df = df.merge(order_items, on="order_id", how="left") #pedido + cliente + item + preço + frete.

df = df.merge(products, on="product_id", how="left") #categoria do produto.

df = df.merge(category_translation, on="product_category_name", how="left") #categoria traduzida.

df = df.merge(reviews[["order_id","review_score"]], on="order_id", how="left") #avaliação do cliente.

df.shape

df.head()

"""**Tratamento das datas**"""

df["order_purchase_timestamp"] = pd.to_datetime(df["order_purchase_timestamp"])
df["order_approved_at"] = pd.to_datetime(df["order_approved_at"])
df["order_delivered_carrier_date"] = pd.to_datetime(df["order_delivered_carrier_date"])
df["order_delivered_customer_date"] = pd.to_datetime(df["order_delivered_customer_date"])
df["order_estimated_delivery_date"] = pd.to_datetime(df["order_estimated_delivery_date"])

"""**Calendário**"""

df["ano"] = df["order_purchase_timestamp"].dt.year
df["mes"] = df["order_purchase_timestamp"].dt.month
df["ano_mes"] = df["order_purchase_timestamp"].dt.to_period("M").astype(str)
df["trimestre"] = df["order_purchase_timestamp"].dt.quarter

"""**Logística**"""

df["tempo_aprovacao_dias"] = (
    df["order_approved_at"] - df["order_purchase_timestamp"]
).dt.total_seconds() / 86400

df["tempo_entrega_dias"] = (
    df["order_delivered_customer_date"] - df["order_purchase_timestamp"]
).dt.total_seconds() / 86400

df["tempo_postagem_dias"] = (
    df["order_delivered_carrier_date"] - df["order_approved_at"]
).dt.total_seconds() / 86400

"""**Flag de atraso**"""

df["pedido_atrasado"] = np.where(
    df["order_delivered_customer_date"] > df["order_estimated_delivery_date"],
    1,
    0
)

"""**Valor**"""

df["receita_item"] = df["price"]
df["valor_frete"] = df["freight_value"]
df["valor_total_item"] = df["price"] + df["freight_value"]

df[[
    "order_purchase_timestamp",
    "ano",
    "mes",
    "ano_mes",
    "trimestre",
    "tempo_aprovacao_dias",
    "tempo_entrega_dias",
    "tempo_postagem_dias",
    "pedido_atrasado",
    "receita_item",
    "valor_frete",
    "valor_total_item"
]].head()

total_pedidos = df["order_id"].nunique()
total_pedidos

receita_total = df["receita_item"].sum()
receita_total

frete_total = df["valor_frete"].sum()
frete_total

valor_total_geral = df["valor_total_item"].sum()
valor_total_geral

ticket_por_pedido = df.groupby("order_id")["valor_total_item"].sum()
ticket_medio = ticket_por_pedido.mean()
ticket_medio

review_medio = df.groupby("order_id")["review_score"].max().mean()
review_medio

atraso_por_pedido = df.groupby("order_id")["pedido_atrasado"].max()
percentual_atraso = atraso_por_pedido.mean() * 100
percentual_atraso

percentual_entregues = (orders["order_status"].eq("delivered").mean()) * 100
percentual_entregues

percentual_cancelados = (orders["order_status"].eq("canceled").mean()) * 100
percentual_cancelados

print(f"Total de pedidos: {total_pedidos:,}")
print(f"Receita total dos produtos: R$ {receita_total:,.2f}")
print(f"Frete total: R$ {frete_total:,.2f}")
print(f"Valor total geral: R$ {valor_total_geral:,.2f}")
print(f"Ticket médio por pedido: R$ {ticket_medio:,.2f}")
print(f"Review médio: {review_medio:.2f}")
print(f"% de pedidos atrasados: {percentual_atraso:.2f}%")
print(f"% de pedidos entregues: {percentual_entregues:.2f}%")
print(f"% de pedidos cancelados: {percentual_cancelados:.2f}%")

pedidos_mes = df.groupby("ano_mes")["order_id"].nunique().reset_index()
pedidos_mes.columns = ["ano_mes", "qtd_pedidos"]

pedidos_mes

receita_mes = df.groupby("ano_mes")["valor_total_item"].sum().reset_index()
receita_mes.columns = ["ano_mes", "receita_total"]

receita_mes

evolucao = pedidos_mes.merge(receita_mes, on="ano_mes")

evolucao

evolucao = evolucao[evolucao["qtd_pedidos"] > 100]

df.to_csv("base_analitica.csv", index=False)

df[["price", "freight_value"]].dtypes

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

plt.rcParams["figure.figsize"] = (12, 5)
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 11
plt.rcParams["xtick.labelsize"] = 9
plt.rcParams["ytick.labelsize"] = 9

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

plt.figure(figsize=(14, 6))

# linha principal
plt.plot(
    evolucao["ano_mes"],
    evolucao["qtd_pedidos"],
    marker="o",
    linewidth=3
)

# títulos
plt.title("Evolução de Pedidos por Mês", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Mês", fontsize=12)
plt.ylabel("Quantidade de Pedidos", fontsize=12)

# eixo X
plt.xticks(rotation=45, ha="right")

# eixo Y formatado com separador de milhar
plt.gca().yaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"{int(x):,}".replace(",", "."))
)

# grid leve
plt.grid(alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# identificar pontos importantes
max_idx = evolucao["qtd_pedidos"].idxmax()
min_idx = evolucao["qtd_pedidos"].idxmin()
last_idx = evolucao.index[-1]

# função de anotação
def anotar(i, texto, offset_y):
    valor = evolucao.loc[i, "qtd_pedidos"]
    mes = evolucao.loc[i, "ano_mes"]

    plt.annotate(
        f"{texto}\n{valor:,.0f}".replace(",", "."),
        xy=(mes, valor),
        xytext=(0, offset_y),
        textcoords="offset points",
        ha="center",
        fontsize=10,
        fontweight="bold",
        arrowprops=dict(arrowstyle="-", lw=0.8, alpha=0.6)
    )

# aplicar anotações
anotar(max_idx, "Maior volume", 30)
anotar(min_idx, "Menor volume", 20)
anotar(last_idx, "Último mês", 20)

# destaque no último ponto
plt.scatter(
    evolucao.loc[last_idx, "ano_mes"],
    evolucao.loc[last_idx, "qtd_pedidos"],
    s=100,
    zorder=5
)

# margem superior (evita sobreposição com título)
plt.ylim(top=evolucao["qtd_pedidos"].max() * 1.15)

plt.tight_layout()

plt.savefig("grafico_1_evolucao_pedidos.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

plt.figure(figsize=(14, 6))

# linha principal (mais destacada)
plt.plot(
    evolucao["ano_mes"],
    evolucao["receita_total"],
    marker="o",
    linewidth=3
)

plt.title("Evolução da Receita por Mês", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Mês", fontsize=12)
plt.ylabel("Receita Total", fontsize=12)

plt.xticks(rotation=45, ha="right")

# eixo Y formatado
plt.gca().yaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"R$ {x/1_000_000:.1f} mi")
)

plt.grid(alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# pontos importantes
max_idx = evolucao["receita_total"].idxmax()
min_idx = evolucao["receita_total"].idxmin()
last_idx = evolucao.index[-1]

# função pra anotar com offset customizado
def anotar(i, texto, offset_y):
    valor = evolucao.loc[i, "receita_total"]
    mes = evolucao.loc[i, "ano_mes"]

    plt.annotate(
        f"{texto}\nR$ {valor/1000:.0f} mil",
        xy=(mes, valor),
        xytext=(0, offset_y),
        textcoords="offset points",
        ha="center",
        fontsize=10,
        fontweight="bold",
        arrowprops=dict(arrowstyle="-", lw=0.8, alpha=0.6)
    )

# ajustes finos de posição
anotar(max_idx, "Maior receita", 30)
anotar(min_idx, "Menor receita", 20)
anotar(last_idx, "Último mês", 20)

# destaque no último ponto
plt.scatter(
    evolucao.loc[last_idx, "ano_mes"],
    evolucao.loc[last_idx, "receita_total"],
    s=100,
    zorder=5
)

# margem extra no topo (resolve o problema do título)
plt.ylim(top=evolucao["receita_total"].max() * 1.15)

plt.tight_layout()

plt.savefig("grafico_2_evolucao_receita.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

plt.figure(figsize=(14, 6))

# linha principal
plt.plot(
    ticket_mes["ano_mes"],
    ticket_mes["ticket_medio"],
    marker="o",
    linewidth=3
)

# títulos
plt.title("Evolução do Ticket Médio por Mês", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Mês", fontsize=12)
plt.ylabel("Ticket Médio (R$)", fontsize=12)

# eixo X
plt.xticks(rotation=45, ha="right")

# grid leve
plt.grid(alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# formatar eixo Y
plt.gca().yaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"R$ {int(x):,}".replace(",", "."))
)

# rótulos organizados (alternando posição)
for i, valor in enumerate(ticket_mes["ticket_medio"]):
    offset = 15 if i % 2 == 0 else -20  # alterna acima/abaixo

    plt.annotate(
        f"R$ {valor:.0f}",
        xy=(ticket_mes["ano_mes"][i], valor),
        xytext=(0, offset),
        textcoords="offset points",
        ha="center",
        fontsize=9,
        fontweight="bold"
    )

# margem superior
plt.ylim(top=ticket_mes["ticket_medio"].max() * 1.10)

plt.tight_layout()

plt.savefig("grafico_3_ticket_medio.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# agregação
categoria_volume = df.groupby("product_category_name_english")["order_id"] \
    .nunique() \
    .sort_values(ascending=False) \
    .head(10)

# ordenar para gráfico horizontal
categoria_volume = categoria_volume.sort_values()

plt.figure(figsize=(12, 6))

ax = plt.barh(
    categoria_volume.index,
    categoria_volume.values
)

# título e labels
plt.title("Top 10 Categorias por Volume de Pedidos", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Quantidade de Pedidos", fontsize=12)
plt.ylabel("Categoria", fontsize=12)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# grid leve no eixo X
plt.grid(axis="x", alpha=0.25)

# formatar eixo X
plt.gca().xaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"{int(x):,}".replace(",", "."))
)

# rótulos nas barras
for i, valor in enumerate(categoria_volume.values):
    plt.text(
        valor + max(categoria_volume.values)*0.01,  # pequeno offset
        i,
        f"{valor:,.0f}".replace(",", "."),
        va="center",
        fontsize=10,
        fontweight="bold"
    )

plt.tight_layout()

plt.savefig("grafico_5_top_categorias_volume.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt

# garantir ordenação correta das faixas
tempo_vs_review = tempo_vs_review.reindex(["até 5", "5-10", "10-15", "15-30", "+30"])

plt.figure(figsize=(10, 5))

ax = plt.bar(
    tempo_vs_review.index,
    tempo_vs_review.values
)

# título e labels
plt.title("Tempo de Entrega vs Avaliação Média", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Faixa de Tempo de Entrega (dias)", fontsize=12)
plt.ylabel("Nota Média", fontsize=12)

plt.xticks(rotation=0)

# grid leve no eixo Y
plt.grid(axis="y", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# rótulos nas barras
for i, valor in enumerate(tempo_vs_review.values):
    plt.text(
        i,
        valor + 0.05,
        f"{valor:.2f}",
        ha="center",
        fontsize=10,
        fontweight="bold"
    )

# limite do eixo Y
plt.ylim(0, 5.2)

plt.tight_layout()

plt.savefig("grafico_6_tempo_entrega_review.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt

# cálculo
atraso_review = df.groupby("pedido_atrasado")["review_score"].mean()

# garantir ordem: 0 = no prazo | 1 = atrasado
atraso_review = atraso_review.reindex([0, 1])

plt.figure(figsize=(8, 5))

ax = plt.bar(
    ["No prazo", "Atrasado"],
    atraso_review.values
)

plt.title("Impacto do Atraso na Avaliação do Cliente", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Status da Entrega", fontsize=12)
plt.ylabel("Avaliação Média", fontsize=12)

# grid leve
plt.grid(axis="y", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# rótulos
for i, valor in enumerate(atraso_review.values):
    plt.text(
        i,
        valor + 0.08,
        f"{valor:.2f}",
        ha="center",
        fontsize=12,
        fontweight="bold"
    )

# linha de referência de boa avaliação
plt.axhline(
    y=4,
    linestyle="--",
    linewidth=1,
    alpha=0.6
)

plt.text(
    1.02,
    4,
    "Referência 4,0",
    va="center",
    fontsize=9
)

plt.ylim(0, 5.3)

plt.tight_layout()

plt.savefig("grafico_7_atraso_review.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# agregação (garantir ordem 1 a 5)
review_dist = df.groupby("review_score")["order_id"].nunique().sort_index()

plt.figure(figsize=(8, 5))

ax = plt.bar(
    review_dist.index.astype(str),
    review_dist.values
)

# título e labels
plt.title("Distribuição das Avaliações dos Clientes", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Nota da Avaliação", fontsize=12)
plt.ylabel("Quantidade de Pedidos", fontsize=12)

# grid leve
plt.grid(axis="y", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# formatar eixo Y
plt.gca().yaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"{int(x):,}".replace(",", "."))
)

# rótulos nas barras
for i, valor in enumerate(review_dist.values):
    plt.text(
        i,
        valor + max(review_dist.values)*0.01,
        f"{valor:,.0f}".replace(",", "."),
        ha="center",
        fontsize=10,
        fontweight="bold"
    )

plt.tight_layout()

plt.savefig("grafico_8_distribuicao_reviews.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# agregação
review_categoria = df.groupby("product_category_name_english")["review_score"] \
    .mean() \
    .sort_values(ascending=True) \
    .head(10)

plt.figure(figsize=(12, 6))

ax = plt.barh(
    review_categoria.index,
    review_categoria.values
)

# título e labels
plt.title("Categorias com Menor Avaliação Média", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Avaliação Média", fontsize=12)
plt.ylabel("Categoria", fontsize=12)

# grid leve no eixo X
plt.grid(axis="x", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# linha de referência (avaliação boa)
plt.axvline(
    x=4,
    linestyle="--",
    linewidth=1,
    alpha=0.6
)

plt.text(
    4.02,
    len(review_categoria) - 0.5,
    "Referência 4,0",
    fontsize=9
)

# rótulos
for i, valor in enumerate(review_categoria.values):
    plt.text(
        valor + 0.05,
        i,
        f"{valor:.2f}",
        va="center",
        fontsize=10,
        fontweight="bold"
    )

plt.xlim(0, 5)

plt.tight_layout()

plt.savefig("grafico_9_menor_review_categoria.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# agregação
estado_receita = df.groupby("customer_state")["valor_total_item"] \
    .sum() \
    .sort_values(ascending=False) \
    .head(10)

# ordenar para gráfico horizontal
estado_receita = estado_receita.sort_values()

plt.figure(figsize=(12, 6))

ax = plt.barh(
    estado_receita.index,
    estado_receita.values
)

# título e labels
plt.title("Top 10 Estados por Receita", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Receita (R$)", fontsize=12)
plt.ylabel("Estado", fontsize=12)

# grid leve no eixo X
plt.grid(axis="x", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# formatar eixo X em milhões
plt.gca().xaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"R$ {x/1_000_000:.1f} mi")
)

# rótulos nas barras
for i, valor in enumerate(estado_receita.values):
    plt.text(
        valor + max(estado_receita.values)*0.01,
        i,
        f"R$ {valor/1_000_000:.1f} mi",
        va="center",
        fontsize=10,
        fontweight="bold"
    )

plt.tight_layout()

plt.savefig("grafico_10_receita_estado.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# agregação
atraso_estado = df.groupby("customer_state")["pedido_atrasado"] \
    .mean() \
    .sort_values(ascending=False) \
    .head(10)

# ordenar para gráfico horizontal
atraso_estado = atraso_estado.sort_values()

plt.figure(figsize=(12, 6))

ax = plt.barh(
    atraso_estado.index,
    atraso_estado.values
)

plt.title("Top 10 Estados com Maior Taxa de Atraso", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Taxa de Atraso", fontsize=12)
plt.ylabel("Estado", fontsize=12)

# eixo X em percentual
plt.gca().xaxis.set_major_formatter(
    mtick.PercentFormatter(1.0)
)

# grid leve
plt.grid(axis="x", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# rótulos nas barras
for i, valor in enumerate(atraso_estado.values):
    plt.text(
        valor + max(atraso_estado.values) * 0.01,
        i,
        f"{valor*100:.1f}%",
        va="center",
        fontsize=10,
        fontweight="bold"
    )

# margem no eixo X
plt.xlim(0, atraso_estado.max() * 1.15)

plt.tight_layout()

plt.savefig("grafico_11_atraso_estado.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# agregação
frete_estado = df.groupby("customer_state")["valor_frete"] \
    .mean() \
    .sort_values(ascending=False) \
    .head(10)

# ordenar para gráfico horizontal
frete_estado = frete_estado.sort_values()

plt.figure(figsize=(12, 6))

ax = plt.barh(
    frete_estado.index,
    frete_estado.values
)

# título e labels
plt.title("Top 10 Estados com Maior Frete Médio", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Frete Médio (R$)", fontsize=12)
plt.ylabel("Estado", fontsize=12)

# grid leve no eixo X
plt.grid(axis="x", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# formatar eixo X em reais
plt.gca().xaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"R$ {x:.0f}")
)

# rótulos nas barras
for i, valor in enumerate(frete_estado.values):
    plt.text(
        valor + max(frete_estado.values)*0.02,
        i,
        f"R$ {valor:.2f}",
        va="center",
        fontsize=10,
        fontweight="bold"
    )

plt.tight_layout()

plt.savefig("grafico_12_frete_medio_estado.png", dpi=300, bbox_inches="tight")

plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# agregação
status_pedidos = orders["order_status"].value_counts()

# ordenar do maior para o menor (melhor leitura)
status_pedidos = status_pedidos.sort_values(ascending=False)

plt.figure(figsize=(10, 5))

ax = plt.bar(
    status_pedidos.index,
    status_pedidos.values
)

# título e labels
plt.title("Distribuição dos Status dos Pedidos", fontsize=16, fontweight="bold", pad=20)
plt.xlabel("Status do Pedido", fontsize=12)
plt.ylabel("Quantidade de Pedidos", fontsize=12)

plt.xticks(rotation=45, ha="right")

# grid leve no eixo Y
plt.grid(axis="y", alpha=0.25)

# remover bordas
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# formatar eixo Y
plt.gca().yaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, _: f"{int(x):,}".replace(",", "."))
)

# rótulos nas barras
for i, valor in enumerate(status_pedidos.values):
    plt.text(
        i,
        valor + max(status_pedidos.values)*0.01,
        f"{valor:,.0f}".replace(",", "."),
        ha="center",
        fontsize=10,
        fontweight="bold"
    )

plt.tight_layout()

plt.savefig("grafico_13_status_pedidos.png", dpi=300, bbox_inches="tight")

plt.show()